---
version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "05:30"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
