require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "**/*_spec.rb"

Naming/MethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - "x"
    - "y"
