plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "**/*_spec.rb"

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - "x"
    - "y"

RSpec/IndexedLet:
  Enabled: false
